# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1612b26bb5af5e3f10218fdf6de78e0850a838844eabf50ac76c573cec1aa62064a35249b484697aed41145ac354261ce0d85947630e13f52a5be441132c6d8c

test:
  secret_key_base: 307f3ecaf14adcfd1f9a052854bb9aa2d74bbf99373946e82df77856efe53e28debd3f430f1a1e8229a8e5dfa683ec79409c9c5ef76feaa2644ebe6198f6ffb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
